### ISSUE TITLE
Menu: many icons missing

### ISSUE THREAD

**Issue by ThanosApostolou** [copycat-killer/awesome-freedesktop#7]
I've tried with different icon themes (Arc, Adwaita, Paper) and various icon sizes but there are always some icons missing:
![screenshot_2018-08-07_11-00-25](https://user-images.githubusercontent.com/21288843/43762645-271c16d2-9a31-11e8-8933-286b4cf38275.png)

**Comment by lcpz** [comment]
As you can read in the [readme](https://github.com/lcpz/awesome-freedesktop#description), the `menu` submodule is an exploit of `menubar`. There could be 3 possible reasons for this:

1. there are applications that simply don't have an icon specification: in this case, it doesn't matter which icon theme you use, unless you manually create the `.desktop` files yourself;
2. it can be caused by `menu` not fetching correctly: in this case, check if the icons appear in `menubar`; if they do, then it's something I can solve; check [here](https://github.com/awesomeWM/awesome/blob/aab582c0a0d464b7621d2fc9cf21d8e501d6e002/awesomerc.lua) on how to use `menubar`;
3. it can be caused by `menubar`: in this case, you should forward the issue to Awesome bug tracker.

**Comment by ThanosApostolou** [comment]
Yeah you are right, it also happens in menubar. I think this is the reported issue: https://github.com/awesomeWM/awesome/issues/1675
